### PR TITLE
Increase MOF compile speed

### PR DESCRIPTION
**Pull request by nyanhp**
#### Pull Request (PR) description

This PR aims to increase MOF compilation speed by importing only required resources for each node. In my customer's environments this reduced build time by nearly 90%.

#### This Pull Request (PR) fixes the following issues

None

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/synedgy/sampler.dscpipeline/18)

### CODE REVIEW

**Comment by raandree** [comment]
@gaelcolas, can you have a look at this and merge it. Looks good to me and works.

**Comment by gaelcolas** [comment]
change looks good but please rebase and fix CHANGELOG conflict.

**Review by gaelcolas — APPROVED** [review]
This looks good. Thanks for rebasing.
I'll merge and fix the publishing later (some doc' issues)

**Comment by gaelcolas** [comment]
Ah no, there's still a conflict apparently @nyanhp

**Comment by raandree** [comment]
Where do you see a conflict?

image

**Comment by gaelcolas** [comment]
image
Here @raandree

**Comment by raandree** [comment]
This is funny. When I look at this PR, it explicitly says that there are no conflicts?!?

image

According to what you see, how many files do have conflicts?

**Comment by gaelcolas** [comment]
Yeah it's weird, not too sure what's going on.
Let me make another change, and see if that changes in GitHub.

**Comment by raandree** [comment]
Thanks for looking into this, @gaelcolas.

**Comment by gaelcolas** [comment]
While I'm still having GitHub issues I'm trying to solve, I've just realised that this change probably breaks compatibility when not using/building RsopCache "first", is that correct?

**Comment by gaelcolas** [comment]
Ignore me, it's past my bedtime... 👎

**Pull request merged**
