### PR TITLE
Redesign of the function `Split-Pipeline`

### PR DESCRIPTION
**Pull request by raandree**
#### This Pull Request (PR) fixes the following issues

Redesign of the function Split-Array. Most of the time it was not working as expected, especially when requesting larger ChunkCounts (see AutomatedLab/AutomatedLab.Common#118).

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/SynEdgy/Sampler.DscPipeline/22)

### CODE REVIEW

**Comment by gaelcolas** [comment]
please fix the formatting of the function parameters to be in line with the DSC Community.
Thanks

**Comment by gaelcolas** [comment]
Yeah, looks like our linting is missing some stuff.
The previous layout is what I expect for the parameters.
image
Ta.

**Comment by raandree** [comment]
Thanks, @gaelcolas, all fixed now.

**Review by gaelcolas — APPROVED** [review]
This looks good.

**Review by gaelcolas — APPROVED** [review]

**Pull request merged**
